spring:
  datasource:
    url: jdbc:postgresql://195.35.24.133:5432/MintdTrace-db
    username: MintdTrace-user
    password: $sUe0SvVq_v4ofm6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
